apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: loki-stack
      version: "2.3.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 1m
  values:
    loki:
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: iam-loki-s3
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: iam-loki-s3
              key: AWS_SECRET_ACCESS_KEY
      config:
        schema_config:
          configs:
            - from: 2021-05-12
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
        storage_config:
          aws:
            s3: s3://us-west-2/bluelightco-loki
            s3forcepathstyle: true
            bucketnames: bluelightco-loki
            region: us-west-2
            insecure: false
            sse_encryption: false
          boltdb_shipper:
            shared_store: s3
            cache_ttl: 24h
    grafana:
      enabled: true
      sidecar:
        datasources:
          enabled: true
      image:
        tag: latest
      grafana.ini:
        users:
          default_theme: light
